bản fix cắt giao diện
quyenhn/LTT_PSDtoHTML pull request #1
Opened 2019-02-14 07:47 UTC by quyenhn

2019-02-14 09:50 UTC, ml-luanvvt requested changes

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +@import "resetcss.css";
không nên @import trong CSS em nhé, dùng thẻ <link luôn

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +	height: auto;
không cần phải set width, height auto em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +	margin: 100px 35px;
nên set padding cho .container thay vì .price-item em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-img{
nếu nó phụ thuộc vào thằng cha thì nên viết như này em nhé
```suggestion
.price-item .price-item-img{
```
áp dụng luôn cho cái khác

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item:nth-child(1) .price-item-img{
không nên dùng dạng thứ tự như này em nhé, nên đặt class

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-featured .price-item-img{
sao không viết ngay sau dòng 23 hả em

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-shape {
đặt tên như này không ý nghĩa em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-featured .sticker {
.sticker phải có prefix em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-subtitle h3{
nên đặt class  cho h3 em nhé, nhỡ sau đổi sang thử div hoặc h4 thì sao

2019-02-14 09:50 UTC, ml-luanvvt commented on css/demo.css
> +.price-item-description ul li{
nên đặt class thay vì dùng trực tiếp ul li em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on css/resetcss.css
> +}
bỏ đi em nhé

2019-02-14 09:50 UTC, ml-luanvvt commented on demo.html
> +		<div class="price-item    price-item-featured">
em nhớ khi làm xong phải format lại cẩn thận nhé, đoạn này nhiều kí tự trống quá

2019-02-14 09:50 UTC, ml-luanvvt commented on demo.html
> +			<button class="btn btn-purple" type="button">BUY TOUR</button>
class `btn-purple` không có ý nghĩa em nhé

2019-02-15 03:55 UTC, quyenhn commented on css/demo.css
> +@import "resetcss.css";
fixed

2019-02-15 03:58 UTC, quyenhn commented on css/demo.css
> +.price-item-shape {
e mới đổi thành wrapper :'(

2019-02-15 06:31 UTC, mvn-luanvu-hn approved these changes

2019-02-15 06:31 UTC, merged